In [2]:
import pandas as pd

In [3]:
import os
print(os.path.exists('../data/time_series.csv'))

False

In [4]:
data_15_min = pd.read_excel('../data/time_series.xlsx', sheet_name='15min')
data_15_min.head()

,Unnamed: 0,Unnamed: 1,AT,AT.1,AT.2,AT.3,AT.4,BE,BE.1,DE,...,HU.2,HU.3,LU,LU.1,NL,NL.1,NL.2,NL.3,NL.4,NL.5
0,NaN,NaN,load,load,price,solar,wind_onshore,load,load,load,...,solar,wind_onshore,load,load,load,load,solar,wind,wind_offshore,wind_onshore
1,NaN,NaN,actual_entsoe_transparency,forecast_entsoe_transparency,day_ahead,generation_actual,generation_actual,actual_entsoe_transparency,forecast_entsoe_transparency,actual_entsoe_transparency,...,generation_actual,generation_actual,actual_entsoe_transparency,forecast_entsoe_transparency,actual_entsoe_transparency,forecast_entsoe_transparency,generation_actual,generation_actual,generation_actual,generation_actual
2,NaN,NaN,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,...,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency,own calculation based on ENTSO-E Transparency,ENTSO-E Transparency,ENTSO-E Transparency
3,NaN,NaN,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/transmission-do...,https://transparency.entsoe.eu/generation/r2/a...,https://transparency.entsoe.eu/generation/r2/a...,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/load-domain/r2/...,...,https://transparency.entsoe.eu/generation/r2/a...,https://transparency.entsoe.eu/generation/r2/a...,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/load-domain/r2/...,https://transparency.entsoe.eu/generation/r2/a...,NaN,https://transparency.entsoe.eu/generation/r2/a...,https://transparency.entsoe.eu/generation/r2/a...
4,NaN,NaN,MW,MW,EUR,MW,MW,MW,MW,MW,...,MW,MW,MW,MW,MW,MW,MW,MW,MW,MW

In [5]:
columns = []
for i in range(len(data_15_min.columns)):
    if data_15_min.columns[i] == 'Unnamed: 0' :
        columns.append('utc_timestamp')
    elif data_15_min.columns[i] == 'Unnamed: 1' :
        columns.append('cet_cest_timestamp')
    else :
        columns.append(str(data_15_min.iloc[0,i]) + '_' + str(data_15_min.iloc[1,i]))

In [6]:
print(columns)

['utc_timestamp', 'cet_cest_timestamp', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'price_day_ahead', 'solar_generation_actual', 'wind_onshore_generation_actual', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_capacity', 'solar_generation_actual', 'solar_profile', 'wind_capacity', 'wind_generation_actual', 'wind_profile', 'wind_offshore_capacity', 'wind_offshore_generation_actual', 'wind_offshore_profile', 'wind_onshore_capacity', 'wind_onshore_generation_actual', 'wind_onshore_profile', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_generation_actual', 'wind_generation_actual', 'wind_offshore_generation_actual', 'wind_onshore_generation_actual', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_generation_actual', 'wind_generation_actual', 'wind_offshore_generation_actual', 'wind_onshore_generation_actual', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_generation_actual', 'wind_onshore_generation_actual', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_generation_actual', 'wind_generation_actual', 'wind_offshore_generation_actual', 'wind_onshore_generation_actual', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_generation_actual', 'wind_onshore_generation_actual', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_generation_actual', 'wind_onshore_generation_actual', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'load_actual_entsoe_transparency', 'load_forecast_entsoe_transparency', 'solar_generation_actual', 'wind_generation_actual', 'wind_offshore_generation_actual', 'wind_onshore_generation_actual']

In [7]:
data_15_min = data_15_min.loc[11:, :]
data_15_min.head()

,Unnamed: 0,Unnamed: 1,AT,AT.1,AT.2,AT.3,AT.4,BE,BE.1,DE,...,HU.2,HU.3,LU,LU.1,NL,NL.1,NL.2,NL.3,NL.4,NL.5
11,2015-01-01 00:15:00,2015-01-01 01:15:00,5966.8,6692.23,61.72,NaN,69.96,9575.73,10028.56,41517.72,...,NaN,12.22,407,368,9524,9081.49,NaN,1447.2,144.72,1302.48
12,2015-01-01 00:30:00,2015-01-01 01:30:00,5935.6,6722.06,28,NaN,69.8,9494.09,9877.94,41179.17,...,NaN,13.27,401,360,9407,8932.06,NaN,1467.52,146.75,1320.77
13,2015-01-01 00:45:00,2015-01-01 01:45:00,5934.4,6689.71,15.68,NaN,65.85,9382.5,9783.68,40756.4,...,NaN,15.67,396,358,9271,8796.28,NaN,1439,143.9,1295.1
14,2015-01-01 01:00:00,2015-01-01 02:00:00,5750.8,6632.8,65.08,NaN,62.23,9349.16,9675.46,40617.76,...,NaN,15.35,392,350,9148,8712.72,NaN,1422.67,142.27,1280.4
15,2015-01-01 01:15:00,2015-01-01 02:15:00,5777.6,6572.9,54.18,NaN,62.87,9213.16,9578.02,40312.25,...,NaN,17.6,384,350,9025,8631.36,NaN,1428.52,142.85,1285.67

In [8]:
data_15_min.columns = columns
data_15_min = data_15_min.reset_index(drop=True)
data_15_min.head()

,utc_timestamp,cet_cest_timestamp,load_actual_entsoe_transparency,load_forecast_entsoe_transparency,price_day_ahead,solar_generation_actual,wind_onshore_generation_actual,load_actual_entsoe_transparency,load_forecast_entsoe_transparency,load_actual_entsoe_transparency,...,solar_generation_actual,wind_onshore_generation_actual,load_actual_entsoe_transparency,load_forecast_entsoe_transparency,load_actual_entsoe_transparency,load_forecast_entsoe_transparency,solar_generation_actual,wind_generation_actual,wind_offshore_generation_actual,wind_onshore_generation_actual
0,2015-01-01 00:15:00,2015-01-01 01:15:00,5966.8,6692.23,61.72,NaN,69.96,9575.73,10028.56,41517.72,...,NaN,12.22,407,368,9524,9081.49,NaN,1447.2,144.72,1302.48
1,2015-01-01 00:30:00,2015-01-01 01:30:00,5935.6,6722.06,28,NaN,69.8,9494.09,9877.94,41179.17,...,NaN,13.27,401,360,9407,8932.06,NaN,1467.52,146.75,1320.77
2,2015-01-01 00:45:00,2015-01-01 01:45:00,5934.4,6689.71,15.68,NaN,65.85,9382.5,9783.68,40756.4,...,NaN,15.67,396,358,9271,8796.28,NaN,1439,143.9,1295.1
3,2015-01-01 01:00:00,2015-01-01 02:00:00,5750.8,6632.8,65.08,NaN,62.23,9349.16,9675.46,40617.76,...,NaN,15.35,392,350,9148,8712.72,NaN,1422.67,142.27,1280.4
4,2015-01-01 01:15:00,2015-01-01 02:15:00,5777.6,6572.9,54.18,NaN,62.87,9213.16,9578.02,40312.25,...,NaN,17.6,384,350,9025,8631.36,NaN,1428.52,142.85,1285.67

In [10]:
data_15_min['utc_timestamp'] = pd.to_datetime(data_15_min['utc_timestamp'], format='%Y-%m-%d %H:%M:%S')
data_15_min.set_index('utc_timestamp', inplace=True)

In [9]:
print(data_15_min.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201599 entries, 0 to 201598
Data columns (total 61 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   utc_timestamp                      201599 non-null  object
 1   cet_cest_timestamp                 201599 non-null  object
 2   load_actual_entsoe_transparency    201598 non-null  object
 3   load_forecast_entsoe_transparency  201598 non-null  object
 4   price_day_ahead                    131378 non-null  object
 5   solar_generation_actual            201352 non-null  object
 6   wind_onshore_generation_actual     201406 non-null  object
 7   load_actual_entsoe_transparency    201598 non-null  object
 8   load_forecast_entsoe_transparency  201502 non-null  object
 9   load_actual_entsoe_transparency    201598 non-null  object
 10  load_forecast_entsoe_transparency  201502 non-null  object
 11  solar_capacity                     175195 non-null  object
 12  solar_generation_actual            201184 non-null  object
 13  solar_profile                      174783 non-null  object
 14  wind_capacity                      175195 non-null  object
 15  wind_generation_actual             201300 non-null  object
 16  wind_profile                       174897 non-null  object
 17  wind_offshore_capacity             175195 non-null  object
 18  wind_offshore_generation_actual    201300 non-null  object
 19  wind_offshore_profile              174897 non-null  object
 20  wind_onshore_capacity              175195 non-null  object
 21  wind_onshore_generation_actual     201310 non-null  object
 22  wind_onshore_profile               174907 non-null  object
 23  load_actual_entsoe_transparency    201598 non-null  object
 24  load_forecast_entsoe_transparency  201598 non-null  object
 25  solar_generation_actual            201541 non-null  object
 26  wind_generation_actual             201598 non-null  object
 27  wind_offshore_generation_actual    201598 non-null  object
 28  wind_onshore_generation_actual     201598 non-null  object
 29  load_actual_entsoe_transparency    70095 non-null   object
 30  load_forecast_entsoe_transparency  66622 non-null   object
 31  solar_generation_actual            70153 non-null   object
 32  wind_generation_actual             70182 non-null   object
 33  wind_offshore_generation_actual    70182 non-null   object
 34  wind_onshore_generation_actual     70182 non-null   object
 35  load_actual_entsoe_transparency    201598 non-null  object
 36  load_forecast_entsoe_transparency  201598 non-null  object
 37  solar_generation_actual            201544 non-null  object
 38  wind_onshore_generation_actual     201598 non-null  object
 39  load_actual_entsoe_transparency    201598 non-null  object
 40  load_forecast_entsoe_transparency  201598 non-null  object
 41  solar_generation_actual            201568 non-null  object
 42  wind_generation_actual             201598 non-null  object
 43  wind_offshore_generation_actual    201598 non-null  object
 44  wind_onshore_generation_actual     201598 non-null  object
 45  load_actual_entsoe_transparency    201598 non-null  object
 46  load_forecast_entsoe_transparency  201502 non-null  object
 47  solar_generation_actual            201542 non-null  object
 48  wind_onshore_generation_actual     201598 non-null  object
 49  load_actual_entsoe_transparency    201598 non-null  object
 50  load_forecast_entsoe_transparency  201410 non-null  object
 51  solar_generation_actual            35859 non-null   object
 52  wind_onshore_generation_actual     193021 non-null  object
 53  load_actual_entsoe_transparency    198794 non-null  object
 54  load_forecast_entsoe_transparency  197182 non-null  object
 55  load_actual_entsoe_transparency    201598 non-null  object
 56  load_forecast_entsoe_transparency  201598 non-null  object
 57  solar_generation_actual            181382 non-null  object
 58  wind_generation_actual             193733 non-null  object
 59  wind_offshore_generation_actual    193733 non-null  object
 60  wind_onshore_generation_actual     200901 non-null  object
dtypes: object(61)
memory usage: 93.8+ MB
None